name: Despliegue de la aplicación

on:
  push:
    branches:
      - main

env:
  APP_NAME: mi-aplicacion

jobs:
  deploy:
    name: Desplegar aplicación
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [DEV, STAGING, PRODUCTION]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and deploy
        run: |
          npm install
          npm run build
          deploy-script --env=$ENVIRONMENT \
          
    inputs:
      environment:
        description: 'Selecciona un entorno'
        required: true
        default: 'DEV'
        options: ['DEV', 'STAGING', 'PRODUCTION']
